version: '3.4'
services:
  back:
    container_name: saegus-back
    restart: always
    build:
      context: ./back
      dockerfile: Dockerfile.dev
    ports:
      - ${BACK_PORT}:${BACK_PORT}
    volumes:
      - ./back/src:/app/src
    environment:
      - PORT=${BACK_PORT}
      - DOMAIN=${BACK_DOMAIN}
      - ORIGIN=${ORIGIN}
      - MONGODB_URI=${BACK_MONGODB_URI}
      - TOKEN_SECRET=${BACK_TOKEN_SECRET}
    
  front:
    container_name: saegus-front
    restart: always
    depends_on:
      - back
    build: ./front
    ports:
      - 3000:3000
    volumes:
      - ./front/src:/app/src
    environment:
      - REACT_APP_API_URL=${BACK_DOMAIN}:${BACK_PORT}

  # back_test:
  #   container_name: saegus-test
  #   restart: always
  #   build:
  #     context: ./back
  #     dockerfile: Dockerfile.dev
  #   ports:
  #     - ${TEST_PORT}:${TEST_PORT}
  #   volumes:
  #     - ./back/src:/app/src
  #   environment:
  #     - PORT=${TEST_PORT}
  #     - DOMAIN=${BACK_DOMAIN}
  #     - ORIGIN=${ORIGIN}
  #     - MONGODB_URI=${BACK_MONGODB_URI}
  #     - TOKEN_SECRET=${BACK_TOKEN_SECRET}
  #     - API_DOMAIN=back
  #     - API_PORT=${BACK_PORT}
  #   depends_on:
  #     - front
  #   command: ["npm", "run", "test:watch"]