FROM node:17

WORKDIR /app

RUN apt-get update -y && apt-get upgrade -y 

COPY package*.json ./
COPY tsconfig.json ./
# COPY .env ./

COPY src ./src
RUN ls -a
RUN npm install

EXPOSE 5001

CMD [ "npm", "run", "dev:ts-node-dev" ]